# See https://www.git-town.com/configuration-file for details

[branches]
main = "main"
order = "asc"

[create]
new-branch-type = "feature"
share-new-branches = "propose"
stash = true

[ship]
delete-tracking-branch = true
strategy = "always-merge"

[sync]
auto-sync = true
feature-strategy = "merge"
perennial-strategy = "rebase"
prototype-strategy = "rebase"
push-branches = false
push-hook = true
tags = false
upstream = true
