# See https://www.git-town.com/configuration-file for details

[branches]
main = "main"
order = "asc"

[create]
new-branch-type = "feature"
share-new-branches = "no"
stash = false

[hosting]
dev-remote = "origin"
github-connector = "gh" # or "api"


[ship]
delete-tracking-branch = false
strategy = "api"

[sync]
feature-strategy = "merge"
perennial-strategy = "rebase"
prototype-strategy = "rebase"
push-hook = true
tags = true
upstream = true